// GENERATED, do not hand-edit. Run: node generate.mjs --set <set.json>
//
// Import from the root for a single icon (the bundler keeps only that module),
// or from a category when you want the group:
//   import { IconMapPin } from "@<scope>/icons";
//   import { IconMapPin } from "@<scope>/icons/categories/map";

export type { Icon, IconProps } from "./icon";

export { IconAbc } from "./icons/IconAbc";
export { IconActivity } from "./icons/IconActivity";
export { IconActivityHeartbeat } from "./icons/IconActivityHeartbeat";
export { IconAd } from "./icons/IconAd";
export { IconAddressBook } from "./icons/IconAddressBook";
export { IconAdjustmentsAlt } from "./icons/IconAdjustmentsAlt";
export { IconAdjustmentsHorizontal } from "./icons/IconAdjustmentsHorizontal";
export { IconAffiliate } from "./icons/IconAffiliate";
export { IconAlertCircle } from "./icons/IconAlertCircle";
export { IconAlertHexagon } from "./icons/IconAlertHexagon";
export { IconAlertOctagon } from "./icons/IconAlertOctagon";
export { IconAlertTriangle } from "./icons/IconAlertTriangle";
export { IconAlien } from "./icons/IconAlien";
export { IconAlignLeft } from "./icons/IconAlignLeft";
export { IconAnchor } from "./icons/IconAnchor";
export { IconAntenna } from "./icons/IconAntenna";
export { IconApi } from "./icons/IconApi";
export { IconAppWindow } from "./icons/IconAppWindow";
export { IconApps } from "./icons/IconApps";
export { IconArchive } from "./icons/IconArchive";
export { IconArchiveOff } from "./icons/IconArchiveOff";
export { IconArmchair } from "./icons/IconArmchair";
export { IconArrowBackUp } from "./icons/IconArrowBackUp";
export { IconArrowBigDownLine } from "./icons/IconArrowBigDownLine";
export { IconArrowDown } from "./icons/IconArrowDown";
export { IconArrowDownToArc } from "./icons/IconArrowDownToArc";
export { IconArrowForward } from "./icons/IconArrowForward";
export { IconArrowForwardUp } from "./icons/IconArrowForwardUp";
export { IconArrowLeft } from "./icons/IconArrowLeft";
export { IconArrowMerge } from "./icons/IconArrowMerge";
export { IconArrowRamp } from "./icons/IconArrowRamp";
export { IconArrowRight } from "./icons/IconArrowRight";
export { IconArrowUp } from "./icons/IconArrowUp";
export { IconArrowUpRight } from "./icons/IconArrowUpRight";
export { IconArrowsLeftRight } from "./icons/IconArrowsLeftRight";
export { IconArrowsMaximize } from "./icons/IconArrowsMaximize";
export { IconArrowsRightLeft } from "./icons/IconArrowsRightLeft";
export { IconArrowsSort } from "./icons/IconArrowsSort";
export { IconAt } from "./icons/IconAt";
export { IconAtom } from "./icons/IconAtom";
export { IconBan } from "./icons/IconBan";
export { IconBarcode } from "./icons/IconBarcode";
export { IconBarrierBlock } from "./icons/IconBarrierBlock";
export { IconBed } from "./icons/IconBed";
export { IconBeer } from "./icons/IconBeer";
export { IconBell } from "./icons/IconBell";
export { IconBellOff } from "./icons/IconBellOff";
export { IconBellRinging } from "./icons/IconBellRinging";
export { IconBike } from "./icons/IconBike";
export { IconBinaryTree2 } from "./icons/IconBinaryTree2";
export { IconBolt } from "./icons/IconBolt";
export { IconBoltFilled } from "./icons/IconBoltFilled";
export { IconBomb } from "./icons/IconBomb";
export { IconBook } from "./icons/IconBook";
export { IconBook2 } from "./icons/IconBook2";
export { IconBookmark } from "./icons/IconBookmark";
export { IconBookmarkOff } from "./icons/IconBookmarkOff";
export { IconBookmarks } from "./icons/IconBookmarks";
export { IconBox } from "./icons/IconBox";
export { IconBraces } from "./icons/IconBraces";
export { IconBrain } from "./icons/IconBrain";
export { IconBriefcase } from "./icons/IconBriefcase";
export { IconBroadcast } from "./icons/IconBroadcast";
export { IconBrowser } from "./icons/IconBrowser";
export { IconBrush } from "./icons/IconBrush";
export { IconBug } from "./icons/IconBug";
export { IconBugFilled } from "./icons/IconBugFilled";
export { IconBugOff } from "./icons/IconBugOff";
export { IconBuilding } from "./icons/IconBuilding";
export { IconBuildingArch } from "./icons/IconBuildingArch";
export { IconBuildingBank } from "./icons/IconBuildingBank";
export { IconBuildingBroadcastTower } from "./icons/IconBuildingBroadcastTower";
export { IconBuildingEstate } from "./icons/IconBuildingEstate";
export { IconBuildingFactory } from "./icons/IconBuildingFactory";
export { IconBuildingFactory2 } from "./icons/IconBuildingFactory2";
export { IconBuildingLighthouse } from "./icons/IconBuildingLighthouse";
export { IconBuildingMonument } from "./icons/IconBuildingMonument";
export { IconBuildingSkyscraper } from "./icons/IconBuildingSkyscraper";
export { IconBuildingStore } from "./icons/IconBuildingStore";
export { IconBulb } from "./icons/IconBulb";
export { IconCake } from "./icons/IconCake";
export { IconCalendar } from "./icons/IconCalendar";
export { IconCalendarEvent } from "./icons/IconCalendarEvent";
export { IconCalendarTime } from "./icons/IconCalendarTime";
export { IconCamera } from "./icons/IconCamera";
export { IconCar } from "./icons/IconCar";
export { IconCarCrash } from "./icons/IconCarCrash";
export { IconCast } from "./icons/IconCast";
export { IconCertificate } from "./icons/IconCertificate";
export { IconChartArcs } from "./icons/IconChartArcs";
export { IconChartArea } from "./icons/IconChartArea";
export { IconChartBar } from "./icons/IconChartBar";
export { IconChartLine } from "./icons/IconChartLine";
export { IconCheck } from "./icons/IconCheck";
export { IconChevronDown } from "./icons/IconChevronDown";
export { IconChevronLeft } from "./icons/IconChevronLeft";
export { IconChevronRight } from "./icons/IconChevronRight";
export { IconChevronUp } from "./icons/IconChevronUp";
export { IconCircle } from "./icons/IconCircle";
export { IconCircleCheck } from "./icons/IconCircleCheck";
export { IconCircleCheckFilled } from "./icons/IconCircleCheckFilled";
export { IconCircleDashed } from "./icons/IconCircleDashed";
export { IconCircleDot } from "./icons/IconCircleDot";
export { IconCircleOff } from "./icons/IconCircleOff";
export { IconCirclePlus } from "./icons/IconCirclePlus";
export { IconCircleX } from "./icons/IconCircleX";
export { IconClipboard } from "./icons/IconClipboard";
export { IconClipboardList } from "./icons/IconClipboardList";
export { IconClipboardPlus } from "./icons/IconClipboardPlus";
export { IconClock } from "./icons/IconClock";
export { IconClockExclamation } from "./icons/IconClockExclamation";
export { IconClockHour3 } from "./icons/IconClockHour3";
export { IconCloud } from "./icons/IconCloud";
export { IconCloudRain } from "./icons/IconCloudRain";
export { IconCloudStorm } from "./icons/IconCloudStorm";
export { IconCode } from "./icons/IconCode";
export { IconCoin } from "./icons/IconCoin";
export { IconCommand } from "./icons/IconCommand";
export { IconCompass } from "./icons/IconCompass";
export { IconCookie } from "./icons/IconCookie";
export { IconCopy } from "./icons/IconCopy";
export { IconCopyOff } from "./icons/IconCopyOff";
export { IconCornerDownLeft } from "./icons/IconCornerDownLeft";
export { IconCpu } from "./icons/IconCpu";
export { IconCreditCard } from "./icons/IconCreditCard";
export { IconCross } from "./icons/IconCross";
export { IconCrosshair } from "./icons/IconCrosshair";
export { IconCrown } from "./icons/IconCrown";
export { IconCube } from "./icons/IconCube";
export { IconCube3dSphere } from "./icons/IconCube3dSphere";
export { IconCubeUnfolded } from "./icons/IconCubeUnfolded";
export { IconCurrentLocation } from "./icons/IconCurrentLocation";
export { IconDatabase } from "./icons/IconDatabase";
export { IconDeviceCctv } from "./icons/IconDeviceCctv";
export { IconDeviceDesktop } from "./icons/IconDeviceDesktop";
export { IconDeviceFloppy } from "./icons/IconDeviceFloppy";
export { IconDeviceLaptop } from "./icons/IconDeviceLaptop";
export { IconDeviceMobile } from "./icons/IconDeviceMobile";
export { IconDevicesPc } from "./icons/IconDevicesPc";
export { IconDice5 } from "./icons/IconDice5";
export { IconDots } from "./icons/IconDots";
export { IconDotsVertical } from "./icons/IconDotsVertical";
export { IconDownload } from "./icons/IconDownload";
export { IconDrone } from "./icons/IconDrone";
export { IconDroplet } from "./icons/IconDroplet";
export { IconEdit } from "./icons/IconEdit";
export { IconEraser } from "./icons/IconEraser";
export { IconExclamationCircle } from "./icons/IconExclamationCircle";
export { IconExternalLink } from "./icons/IconExternalLink";
export { IconEye } from "./icons/IconEye";
export { IconEyeOff } from "./icons/IconEyeOff";
export { IconEyeSearch } from "./icons/IconEyeSearch";
export { IconFaceId } from "./icons/IconFaceId";
export { IconFile } from "./icons/IconFile";
export { IconFileCertificate } from "./icons/IconFileCertificate";
export { IconFileDownload } from "./icons/IconFileDownload";
export { IconFileExport } from "./icons/IconFileExport";
export { IconFileImport } from "./icons/IconFileImport";
export { IconFileInfo } from "./icons/IconFileInfo";
export { IconFileText } from "./icons/IconFileText";
export { IconFileTypeCsv } from "./icons/IconFileTypeCsv";
export { IconFileZip } from "./icons/IconFileZip";
export { IconFilter } from "./icons/IconFilter";
export { IconFingerprint } from "./icons/IconFingerprint";
export { IconFish } from "./icons/IconFish";
export { IconFlag } from "./icons/IconFlag";
export { IconFlame } from "./icons/IconFlame";
export { IconFlask } from "./icons/IconFlask";
export { IconFocus2 } from "./icons/IconFocus2";
export { IconFocusCentered } from "./icons/IconFocusCentered";
export { IconFolder } from "./icons/IconFolder";
export { IconFolderOpen } from "./icons/IconFolderOpen";
export { IconFolderPlus } from "./icons/IconFolderPlus";
export { IconFolderSearch } from "./icons/IconFolderSearch";
export { IconFolders } from "./icons/IconFolders";
export { IconGenderFemale } from "./icons/IconGenderFemale";
export { IconGenderMale } from "./icons/IconGenderMale";
export { IconGhost } from "./icons/IconGhost";
export { IconGhost2 } from "./icons/IconGhost2";
export { IconGitMerge } from "./icons/IconGitMerge";
export { IconGridDots } from "./icons/IconGridDots";
export { IconGripVertical } from "./icons/IconGripVertical";
export { IconHash } from "./icons/IconHash";
export { IconHeart } from "./icons/IconHeart";
export { IconHeartHandshake } from "./icons/IconHeartHandshake";
export { IconHeartbeat } from "./icons/IconHeartbeat";
export { IconHelpCircle } from "./icons/IconHelpCircle";
export { IconHierarchy } from "./icons/IconHierarchy";
export { IconHistory } from "./icons/IconHistory";
export { IconHome } from "./icons/IconHome";
export { IconHome2 } from "./icons/IconHome2";
export { IconHomeSearch } from "./icons/IconHomeSearch";
export { IconId } from "./icons/IconId";
export { IconInfinity } from "./icons/IconInfinity";
export { IconInfoCircle } from "./icons/IconInfoCircle";
export { IconKey } from "./icons/IconKey";
export { IconLanguage } from "./icons/IconLanguage";
export { IconLayersIntersect } from "./icons/IconLayersIntersect";
export { IconLayersLinked } from "./icons/IconLayersLinked";
export { IconLayoutDashboard } from "./icons/IconLayoutDashboard";
export { IconLayoutGrid } from "./icons/IconLayoutGrid";
export { IconLayoutSidebar } from "./icons/IconLayoutSidebar";
export { IconLeaf } from "./icons/IconLeaf";
export { IconLetterCase } from "./icons/IconLetterCase";
export { IconLibrary } from "./icons/IconLibrary";
export { IconLicense } from "./icons/IconLicense";
export { IconLifebuoy } from "./icons/IconLifebuoy";
export { IconLink } from "./icons/IconLink";
export { IconLinkOff } from "./icons/IconLinkOff";
export { IconListCheck } from "./icons/IconListCheck";
export { IconListDetails } from "./icons/IconListDetails";
export { IconListNumbers } from "./icons/IconListNumbers";
export { IconLoader2 } from "./icons/IconLoader2";
export { IconLock } from "./icons/IconLock";
export { IconLockExclamation } from "./icons/IconLockExclamation";
export { IconLockOpen } from "./icons/IconLockOpen";
export { IconLogin } from "./icons/IconLogin";
export { IconLogout } from "./icons/IconLogout";
export { IconMail } from "./icons/IconMail";
export { IconMap } from "./icons/IconMap";
export { IconMap2 } from "./icons/IconMap2";
export { IconMapPin } from "./icons/IconMapPin";
export { IconMapPinPlus } from "./icons/IconMapPinPlus";
export { IconMapSearch } from "./icons/IconMapSearch";
export { IconMaximize } from "./icons/IconMaximize";
export { IconMessage } from "./icons/IconMessage";
export { IconMessage2 } from "./icons/IconMessage2";
export { IconMessageCircle } from "./icons/IconMessageCircle";
export { IconMessages } from "./icons/IconMessages";
export { IconMicrophone } from "./icons/IconMicrophone";
export { IconMicroscope } from "./icons/IconMicroscope";
export { IconMinimize } from "./icons/IconMinimize";
export { IconMinus } from "./icons/IconMinus";
export { IconMoon } from "./icons/IconMoon";
export { IconMountain } from "./icons/IconMountain";
export { IconMovie } from "./icons/IconMovie";
export { IconNavigation } from "./icons/IconNavigation";
export { IconNetwork } from "./icons/IconNetwork";
export { IconNews } from "./icons/IconNews";
export { IconNote } from "./icons/IconNote";
export { IconNotes } from "./icons/IconNotes";
export { IconPackage } from "./icons/IconPackage";
export { IconPalette } from "./icons/IconPalette";
export { IconPaperclip } from "./icons/IconPaperclip";
export { IconPencil } from "./icons/IconPencil";
export { IconPhone } from "./icons/IconPhone";
export { IconPhoto } from "./icons/IconPhoto";
export { IconPhotoCheck } from "./icons/IconPhotoCheck";
export { IconPhotoSearch } from "./icons/IconPhotoSearch";
export { IconPhotoStar } from "./icons/IconPhotoStar";
export { IconPin } from "./icons/IconPin";
export { IconPinFilled } from "./icons/IconPinFilled";
export { IconPlane } from "./icons/IconPlane";
export { IconPlaneInflight } from "./icons/IconPlaneInflight";
export { IconPlaneOff } from "./icons/IconPlaneOff";
export { IconPlaneTilt } from "./icons/IconPlaneTilt";
export { IconPlayerPause } from "./icons/IconPlayerPause";
export { IconPlayerPlay } from "./icons/IconPlayerPlay";
export { IconPlayerPlayFilled } from "./icons/IconPlayerPlayFilled";
export { IconPlayerStop } from "./icons/IconPlayerStop";
export { IconPlayerStopFilled } from "./icons/IconPlayerStopFilled";
export { IconPlug } from "./icons/IconPlug";
export { IconPlugConnected } from "./icons/IconPlugConnected";
export { IconPlugX } from "./icons/IconPlugX";
export { IconPlus } from "./icons/IconPlus";
export { IconPointFilled } from "./icons/IconPointFilled";
export { IconPolygon } from "./icons/IconPolygon";
export { IconPrinter } from "./icons/IconPrinter";
export { IconPuzzle } from "./icons/IconPuzzle";
export { IconQrcode } from "./icons/IconQrcode";
export { IconQuestionMark } from "./icons/IconQuestionMark";
export { IconQuote } from "./icons/IconQuote";
export { IconRadar } from "./icons/IconRadar";
export { IconRadar2 } from "./icons/IconRadar2";
export { IconRadio } from "./icons/IconRadio";
export { IconRadioactive } from "./icons/IconRadioactive";
export { IconReceipt } from "./icons/IconReceipt";
export { IconReceiptTax } from "./icons/IconReceiptTax";
export { IconRefresh } from "./icons/IconRefresh";
export { IconRegex } from "./icons/IconRegex";
export { IconReload } from "./icons/IconReload";
export { IconRepeat } from "./icons/IconRepeat";
export { IconReport } from "./icons/IconReport";
export { IconRestore } from "./icons/IconRestore";
export { IconRipple } from "./icons/IconRipple";
export { IconRoad } from "./icons/IconRoad";
export { IconRobot } from "./icons/IconRobot";
export { IconRocket } from "./icons/IconRocket";
export { IconRotate } from "./icons/IconRotate";
export { IconRotate3d } from "./icons/IconRotate3d";
export { IconRoute } from "./icons/IconRoute";
export { IconRoute2 } from "./icons/IconRoute2";
export { IconRouteAltLeft } from "./icons/IconRouteAltLeft";
export { IconRouter } from "./icons/IconRouter";
export { IconRuler } from "./icons/IconRuler";
export { IconRuler2 } from "./icons/IconRuler2";
export { IconSailboat } from "./icons/IconSailboat";
export { IconSatellite } from "./icons/IconSatellite";
export { IconScale } from "./icons/IconScale";
export { IconScan } from "./icons/IconScan";
export { IconSchool } from "./icons/IconSchool";
export { IconScissors } from "./icons/IconScissors";
export { IconScreenShare } from "./icons/IconScreenShare";
export { IconSearch } from "./icons/IconSearch";
export { IconSelectAll } from "./icons/IconSelectAll";
export { IconSend } from "./icons/IconSend";
export { IconServer } from "./icons/IconServer";
export { IconSettings } from "./icons/IconSettings";
export { IconSettings2 } from "./icons/IconSettings2";
export { IconShadow } from "./icons/IconShadow";
export { IconShield } from "./icons/IconShield";
export { IconShieldCheck } from "./icons/IconShieldCheck";
export { IconShieldExclamation } from "./icons/IconShieldExclamation";
export { IconShieldHalf } from "./icons/IconShieldHalf";
export { IconShieldHalfFilled } from "./icons/IconShieldHalfFilled";
export { IconShieldLock } from "./icons/IconShieldLock";
export { IconShieldOff } from "./icons/IconShieldOff";
export { IconShieldX } from "./icons/IconShieldX";
export { IconShip } from "./icons/IconShip";
export { IconShoppingBag } from "./icons/IconShoppingBag";
export { IconShoppingCart } from "./icons/IconShoppingCart";
export { IconSignature } from "./icons/IconSignature";
export { IconSortAZ } from "./icons/IconSortAZ";
export { IconSparkles } from "./icons/IconSparkles";
export { IconSpy } from "./icons/IconSpy";
export { IconSquare } from "./icons/IconSquare";
export { IconStack2 } from "./icons/IconStack2";
export { IconStack3 } from "./icons/IconStack3";
export { IconStar } from "./icons/IconStar";
export { IconStarFilled } from "./icons/IconStarFilled";
export { IconStarOff } from "./icons/IconStarOff";
export { IconSubtask } from "./icons/IconSubtask";
export { IconSun } from "./icons/IconSun";
export { IconSunElectricity } from "./icons/IconSunElectricity";
export { IconSunrise } from "./icons/IconSunrise";
export { IconSword } from "./icons/IconSword";
export { IconTableOptions } from "./icons/IconTableOptions";
export { IconTag } from "./icons/IconTag";
export { IconTags } from "./icons/IconTags";
export { IconTarget } from "./icons/IconTarget";
export { IconTargetArrow } from "./icons/IconTargetArrow";
export { IconTerminal } from "./icons/IconTerminal";
export { IconTerminal2 } from "./icons/IconTerminal2";
export { IconTextCaption } from "./icons/IconTextCaption";
export { IconTextRecognition } from "./icons/IconTextRecognition";
export { IconTextWrap } from "./icons/IconTextWrap";
export { IconThumbDown } from "./icons/IconThumbDown";
export { IconThumbUp } from "./icons/IconThumbUp";
export { IconTimeline } from "./icons/IconTimeline";
export { IconTool } from "./icons/IconTool";
export { IconTools } from "./icons/IconTools";
export { IconToolsKitchen2 } from "./icons/IconToolsKitchen2";
export { IconTopologyStar3 } from "./icons/IconTopologyStar3";
export { IconTrain } from "./icons/IconTrain";
export { IconTrash } from "./icons/IconTrash";
export { IconTrashX } from "./icons/IconTrashX";
export { IconTrees } from "./icons/IconTrees";
export { IconTrendingDown } from "./icons/IconTrendingDown";
export { IconTrendingUp } from "./icons/IconTrendingUp";
export { IconTruck } from "./icons/IconTruck";
export { IconUnlink } from "./icons/IconUnlink";
export { IconUpload } from "./icons/IconUpload";
export { IconUser } from "./icons/IconUser";
export { IconUserCheck } from "./icons/IconUserCheck";
export { IconUserCircle } from "./icons/IconUserCircle";
export { IconUserExclamation } from "./icons/IconUserExclamation";
export { IconUserOff } from "./icons/IconUserOff";
export { IconUserPlus } from "./icons/IconUserPlus";
export { IconUserScan } from "./icons/IconUserScan";
export { IconUserSearch } from "./icons/IconUserSearch";
export { IconUsers } from "./icons/IconUsers";
export { IconUsersGroup } from "./icons/IconUsersGroup";
export { IconVariable } from "./icons/IconVariable";
export { IconVectorTriangle } from "./icons/IconVectorTriangle";
export { IconVideo } from "./icons/IconVideo";
export { IconVideoOff } from "./icons/IconVideoOff";
export { IconVirus } from "./icons/IconVirus";
export { IconWall } from "./icons/IconWall";
export { IconWallet } from "./icons/IconWallet";
export { IconWand } from "./icons/IconWand";
export { IconWaveSine } from "./icons/IconWaveSine";
export { IconWaveSquare } from "./icons/IconWaveSquare";
export { IconWifi } from "./icons/IconWifi";
export { IconWifiOff } from "./icons/IconWifiOff";
export { IconWind } from "./icons/IconWind";
export { IconWorld } from "./icons/IconWorld";
export { IconWorldSearch } from "./icons/IconWorldSearch";
export { IconWorldWww } from "./icons/IconWorldWww";
export { IconX } from "./icons/IconX";
export { IconZoomIn } from "./icons/IconZoomIn";
export { IconZoomOut } from "./icons/IconZoomOut";

// Brand marks keep their real logo: this set has none, and drawing one by hand
// is worse than shipping the real mark.
export {
    IconBrandAdobe,
    IconBrandApple,
    IconBrandBluesky,
    IconBrandDiscord,
    IconBrandDocker,
    IconBrandFacebook,
    IconBrandFirefox,
    IconBrandGithub,
    IconBrandGitlab,
    IconBrandGoogle,
    IconBrandInstagram,
    IconBrandLinkedin,
    IconBrandMastodon,
    IconBrandPatreon,
    IconBrandPaypal,
    IconBrandPinterest,
    IconBrandPython,
    IconBrandReddit,
    IconBrandRumble,
    IconBrandSnapchat,
    IconBrandSpotify,
    IconBrandTelegram,
    IconBrandTiktok,
    IconBrandTwitch,
    IconBrandUbuntu,
    IconBrandWindows,
    IconBrandWordpress,
    IconBrandX,
    IconBrandYoutube,
    IconCurrencyBitcoin,
    IconCurrencyEthereum
} from "@tabler/icons-react";
