/**
 * Guardrails hook deployment. When the `guardrails` toggle is on (default), enigma wires
 * a post-write hook into each agent so that after an edit the convention rules run and any
 * violation is fed back to the model. The engine is bundled in enigma, so the hook simply
 * invokes the hidden `enigma __guardrails-hook` command (which reads the PostToolUse
 * payload from stdin) - no runner file to maintain.
 *
 * Wiring per agent (Codex has no per-edit hook mechanism, so it is skipped, like auto-lint):
 *  - Claude Code: a PostToolUse hook in settings.json (matcher Edit|Write|MultiEdit|
 *    NotebookEdit); the command exits 2 with stderr on a BLOCK violation, which Claude
 *    feeds to the model.
 *  - opencode: an auto-loaded plugin whose tool.execute.after pipes the edited file to
 *    the same command and appends the findings to the tool output the model sees.
 *  - Kimi Code: skipped by capability. It has a PostToolUse hook, but that event is
 *    observation-only there - "they fire and forget; the main flow is unaffected regardless
 *    of what the script returns" - so the findings would reach nothing, and the only
 *    blockable per-tool event (PreToolUse) fires before the write, when the file on disk is
 *    still the old one. Wiring it would spend a process per edit to produce silence. Kimi
 *    still gets the trim hook, which needs no feedback channel (see trim-deploy.ts).
 *
 * Node-builtins + config/util only (no engine import) so it stays cheap to load and free
 * of cycles - it is the deploy counterpart of the self-contained guardrails.ts engine.
 */

import { enigmaHome } from "./util";
import { join, dirname } from "node:path";
import { claudeGlobalSettings } from "./claude-hooks";
import { readConfig, setEnigmaToggle } from "./config";
import { applyClaudePostEditHook } from "./post-edit-deploy";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";

/** True when guardrails is enabled (default on). */
export function isGuardrailsOn(): boolean {
    return readConfig().config.guardrails;
}

// --- Claude Code: PostToolUse hook in settings.json --------------------------------
//
// Not written here any more. Claude Code starts a process per settings.json entry, and guardrails
// is one of three features that write after an edit, so three entries meant three starts of the
// ~99 MB binary per edit. post-edit-deploy.ts owns the single merged entry and reads this toggle
// itself; the hidden `enigma __guardrails-hook` command it replaces still exists, because the
// opencode plugin below invokes it directly.

// --- opencode: auto-loaded plugin --------------------------------------------------

/** The plugin file path inside an opencode config dir (`<configDir>/plugins/enigma-guardrails.js`). */
function opencodePluginPath(opencodeConfigDir: string): string {
    return join(opencodeConfigDir, "plugins", "enigma-guardrails.js");
}

/**
 * Write (on) or remove (off) the enigma opencode guardrails plugin in an opencode config
 * dir's `plugins/` (auto-loaded by opencode at startup). Returns true when changed.
 */
export function applyOpencodeGuardrailsPlugin(opencodeConfigDir: string, on: boolean): boolean {
    const path = opencodePluginPath(opencodeConfigDir);
    if (on) {
        if (existsSync(path)) return false;
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, opencodePluginSource());
        return true;
    }
    if (!existsSync(path)) return false;
    rmSync(path, { force: true });
    return true;
}

/** opencode plugin source: pipes the edited file to the hidden hook and surfaces its findings. */
function opencodePluginSource(): string {
    return `// Generated by enigma (guardrails). Do not edit; toggle with 'enigma config guardrails off'.
import { spawnSync } from "node:child_process";

const FILE_TOOLS = new Set(["write", "edit", "multiedit", "patch"]);

export const EnigmaGuardrails = async () => ({
    "tool.execute.after": async (input, output) => {
        try {
            if (!FILE_TOOLS.has(input.tool)) return;
            const file = input.args && (input.args.filePath || input.args.path);
            if (!file) return;
            // The command resolves the enigma binary on PATH; shell:true lets Windows resolve enigma.cmd.
            // windowsHide keeps that shell from flashing a console window on every edit.
            const payload = JSON.stringify({ tool_input: { file_path: file } });
            const r = spawnSync("enigma", ["__guardrails-hook"], { input: payload, encoding: "utf8", timeout: 30000, shell: process.platform === "win32", windowsHide: true });
            const findings = ((r.stderr || "") + (r.stdout || "")).trim();
            if (findings) output.output += "\\n\\n[enigma-guardrails]\\n" + findings;
        } catch { /* never break the tool on a guardrails failure */ }
    },
});
`;
}

// --- global apply / per-account mirror / toggle ------------------------------------

/** Global opencode config dir for the default account. */
function opencodeGlobalConfig(): string {
    return join(enigmaHome(), ".config", "opencode");
}

/**
 * Re-assert the global wiring to match the current toggle: add or remove the Claude hook
 * and the opencode plugin. Called on install and on toggle (presence AND absence).
 */
export function applyGuardrailsWiring(): void {
    applyClaudePostEditHook(claudeGlobalSettings());
    applyOpencodeGuardrailsPlugin(opencodeGlobalConfig(), isGuardrailsOn());
}

/**
 * Mirror the guardrails wiring into a managed account's config dir, matching the global
 * toggle (presence AND absence), so `enigma <tool> <account>` behaves like the default.
 * Mirrors only the tools that have a per-account config surface (claude, opencode).
 */
export function mirrorGuardrailsWiring(toolName: string, accountDir: string): void {
    if (toolName === "claude") applyClaudePostEditHook(join(accountDir, "settings.json"));
    else if (toolName === "opencode") applyOpencodeGuardrailsPlugin(join(accountDir, "xdg-config", "opencode"), isGuardrailsOn());
}

/**
 * Set the guardrails toggle and apply the global wiring. Enabling adds the hooks;
 * disabling removes them. Returns the .enigma.json path written.
 */
export function setGuardrails(scope: "global" | "local", on: boolean): string {
    const path = setEnigmaToggle("guardrails", on, scope);
    applyGuardrailsWiring();
    return path;
}
