/**
 * EOF-trimmer hook deployment. When the `trim` toggle is on (default), enigma wires a
 * post-write hook into each agent so the blank line its write tool leaves at the end of a
 * file is removed straight away, in the same turn - which is where this problem is cheapest
 * to fix, long before a commit. The engine is bundled in enigma, so the hook just invokes the
 * hidden `enigma __trim-hook` command (which reads the PostToolUse payload from stdin).
 *
 * The commit-time half is separate and lives in security.ts, which copies dist/trim.js into a
 * repo's .githooks/ as the backstop for edits enigma's hook never saw (a teammate's editor, a
 * generator, a merge).
 *
 * Wiring per agent (Codex has no per-edit hook, so it is skipped):
 *  - Claude Code: a PostToolUse hook in settings.json (matcher Edit|Write|MultiEdit|NotebookEdit).
 *  - opencode: an auto-loaded plugin whose tool.execute.after pipes the edited file to the hook.
 *  - Kimi Code: a PostToolUse hook in config.toml (matcher Write|Edit). Kimi's PostToolUse is
 *    observation-only, which is no obstacle here - the trim is a silent side effect that needs
 *    nothing fed back to the model (it is exactly why trim reaches Kimi and guardrails does not).
 *
 * Node-builtins + config/util only (no engine import), the deploy counterpart of trim.ts.
 */

import { kimiHome } from "./kimi";
import { enigmaHome } from "./util";
import { join, dirname } from "node:path";
import { applyKimiHook } from "./kimi-hooks";
import { claudeGlobalSettings } from "./claude-hooks";
import { readConfig, setEnigmaToggle } from "./config";
import { applyClaudePostEditHook } from "./post-edit-deploy";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";

/** True when the EOF trimmer is enabled (default on). */
export function isTrimOn(): boolean {
    return readConfig().config.trim;
}

// --- Claude Code: PostToolUse hook in settings.json --------------------------------
//
// Not written here any more. Claude Code starts a process per settings.json entry, and the trimmer
// is one of three features that write after an edit, so three entries meant three starts of the
// ~99 MB binary per edit. post-edit-deploy.ts owns the single merged entry and reads this toggle
// itself. Kimi keeps its own entry below: it wires only the trimmer, so there is nothing to merge
// there, and its PostToolUse is observation-only anyway.
//
// The merge also settled an ordering race this file could not settle alone - the trimmer rewrites
// the file that guardrails then scans, and as separate entries the host was free to run them in
// either order. In one process the trimmer goes first (post-edit-hook.ts).

// --- opencode: auto-loaded plugin --------------------------------------------------

/** The plugin file path inside an opencode config dir (`<configDir>/plugins/enigma-trim.js`). */
function opencodePluginPath(opencodeConfigDir: string): string {
    return join(opencodeConfigDir, "plugins", "enigma-trim.js");
}

/**
 * Write (on) or remove (off) the enigma opencode trim plugin in an opencode config dir's
 * `plugins/` (auto-loaded by opencode at startup). Returns true when changed.
 */
export function applyOpencodeTrimPlugin(opencodeConfigDir: string, on: boolean): boolean {
    const path = opencodePluginPath(opencodeConfigDir);
    if (on) {
        if (existsSync(path)) return false;
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, opencodePluginSource());
        return true;
    }
    if (!existsSync(path)) return false;
    rmSync(path, { force: true });
    return true;
}

/** opencode plugin source: pipes the edited file to the hidden hook. It reports nothing - the trim is silent. */
function opencodePluginSource(): string {
    return `// Generated by enigma (trim). Do not edit; toggle with 'enigma config trim off'.
import { spawnSync } from "node:child_process";

const FILE_TOOLS = new Set(["write", "edit", "multiedit", "patch"]);

export const EnigmaTrim = async () => ({
    "tool.execute.after": async (input) => {
        try {
            if (!FILE_TOOLS.has(input.tool)) return;
            const file = input.args && (input.args.filePath || input.args.path);
            if (!file) return;
            // The command resolves the enigma binary on PATH; shell:true lets Windows resolve
            // enigma.cmd, and windowsHide keeps that shell from flashing a console window.
            const payload = JSON.stringify({ tool_input: { file_path: file } });
            spawnSync("enigma", ["__trim-hook"], { input: payload, encoding: "utf8", timeout: 10000, shell: process.platform === "win32", windowsHide: true });
        } catch { /* never break the tool on a trim failure */ }
    },
});
`;
}

// --- Kimi Code: PostToolUse hook in config.toml -------------------------------------

/** Kimi's file-editing tools, as its permission and hook matchers name them. */
const KIMI_HOOK_MATCHER = "Write|Edit";

/**
 * Add (on) or remove (off) the enigma PostToolUse trim hook in a Kimi config.toml,
 * preserving every other hook and setting. Returns true when the file changed.
 */
export function applyKimiTrimHook(configPath: string, on: boolean): boolean {
    const hook = { event: "PostToolUse", matcher: KIMI_HOOK_MATCHER, command: "enigma __trim-hook", timeout: 10 };
    return applyKimiHook(configPath, "__trim-hook", hook, on) === "changed";
}

// --- global apply / per-account mirror / toggle ------------------------------------

/** Global opencode config dir for the default account. */
function opencodeGlobalConfig(): string {
    return join(enigmaHome(), ".config", "opencode");
}

/** Global Kimi config.toml for the default account (kimiHome honors ENIGMA_CONFIG_HOME). */
function kimiGlobalConfig(): string {
    return join(kimiHome(), "config.toml");
}

/**
 * Re-assert the global wiring to match the current toggle: add or remove the Claude hook and
 * the opencode plugin. Called on install and on toggle (presence AND absence).
 */
export function applyTrimWiring(): void {
    const on = isTrimOn();
    applyClaudePostEditHook(claudeGlobalSettings());
    applyOpencodeTrimPlugin(opencodeGlobalConfig(), on);
    applyKimiTrimHook(kimiGlobalConfig(), on);
}

/**
 * Mirror the trim wiring into a managed account's config dir, matching the global toggle
 * (presence AND absence), so `enigma <tool> <account>` behaves like the default.
 */
export function mirrorTrimWiring(toolName: string, accountDir: string): void {
    const on = isTrimOn();
    if (toolName === "claude") applyClaudePostEditHook(join(accountDir, "settings.json"));
    else if (toolName === "opencode") applyOpencodeTrimPlugin(join(accountDir, "xdg-config", "opencode"), on);
    else if (toolName === "kimi") applyKimiTrimHook(join(accountDir, "config.toml"), on);
}

/**
 * Set the trim toggle and apply the global wiring. Enabling adds the hooks; disabling removes
 * them. Returns the .enigma.json path written.
 */
export function setTrim(scope: "global" | "local", on: boolean): string {
    const path = setEnigmaToggle("trim", on, scope);
    applyTrimWiring();
    return path;
}
