// Generated by enigma (relay). Do not edit; set with 'enigma config relay' and 'enigma config relay-at'.
//
// When a turn ends with the context past RELAY_AT tokens, ask the agent for a handoff
// (`enigma handoff save`); when the next turn ends with a fresh one saved for this project, run
// /clear and continue the work from it in the cleared session. Nothing is cleared without a saved
// handoff, and a handoff marked "STATUS: done" ends the relay instead of continuing it. When a
// relay keeps the context (nothing saved, or the work is done), it is not asked again until the
// context has grown by another half of RELAY_AT.
import type { EngineInterface, Register } from "claude-code";

const RELAY_AT = 300000;
const LATEST = "/home/user/.enigma/handoff/latest.json";
/** Relays one session may make: a runaway loop stops instead of clearing forever. */
const MAX_RELAYS = 20;

interface Latest { root: string; savedAt: number; done: boolean; text: string; meta: string; consumedAt: number | null; }

const ASK = [
    "[enigma relay] This conversation is past %TOKENS% tokens and every call re-reads all of it.",
    "Run the /handoff procedure now: save the handoff for the work in progress with `enigma handoff save`",
    "(goal, done, next, decisions, verify, files), then stop. If the work is finished, save it with the line",
    "`STATUS: done`. enigma clears the context and continues from the handoff on its own.",
].join(" ");

const under = (cwd: string, root: string): boolean => {
    const norm = (p: string): string => p.split("\\").join("/").replace(/\/+$/, "").toLowerCase();
    const c = norm(cwd);
    const r = norm(root);
    return c === r || c.startsWith(`${r}/`);
};

/** The newest handoff save, from the pointer `enigma handoff save` writes. */
async function latest($: EngineInterface): Promise<Latest | null> {
    try { return JSON.parse(await $.fs.read(LATEST)) as Latest; } catch { return null; }
}

export const register: Register = (on) => {
    let askedAt = 0;
    let relays = 0;
    let nextAt = RELAY_AT;

    on("turn.complete", async ($, e, next) => {
        const result = await next(e);
        // The main loop only: a subagent's turns and interrupted ones are not a point to relay at.
        if (e.agentId !== undefined || e.reason !== "answer" || relays >= MAX_RELAYS) return result;

        if (askedAt) {
            const asked = askedAt;
            askedAt = 0;
            const saved = await latest($);
            const cwd = await $.session.cwd();
            const kept = async (): Promise<void> => { nextAt = ((await $.session.usage()).context.tokens ?? 0) + Math.round(RELAY_AT / 2); };
            if (!saved || saved.savedAt < asked || !under(cwd, saved.root)) {
                await kept();
                $.ui.toast("enigma relay: no handoff was saved, so the context was kept.");
                return result;
            }
            if (saved.done) {
                await kept();
                $.ui.toast("enigma relay: the work is finished; the context was kept for questions about it.");
                return result;
            }
            relays++;
            nextAt = RELAY_AT;
            void (async () => {
                await $.command.run({ command: "clear" });
                // The session-start hook delivers the handoff after /clear and marks it consumed; when it
                // did not (hook off, another host), the page goes in the prompt itself.
                let delivered = false;
                try { delivered = (JSON.parse(await $.fs.read(saved.meta)) as Latest).consumedAt != null; } catch { /* unreadable: send it */ }
                let page = "";
                if (!delivered) { try { page = `\n\n${await $.fs.read(saved.text)}`; } catch { /* nothing to add */ } }
                await $.prompt.submit({ text: `[enigma relay] The context was cleared to save tokens. Continue the work from the handoff now, starting at its next step.${page}` });
            })();
            return result;
        }

        const { context } = await $.session.usage();
        // Back under the threshold (a manual /clear, a compaction): the next crossing asks again.
        if ((context.tokens ?? 0) < RELAY_AT) nextAt = RELAY_AT;
        if ((context.tokens ?? 0) < nextAt) return result;
        askedAt = Date.now();
        void $.prompt.submit({ text: ASK.replace("%TOKENS%", String(Math.round((context.tokens ?? 0) / 1000) * 1000)) });
        return result;
    });
};
