/**
 * Built-in output filters for shell/tool output, keyed by the command that produced it.
 *
 * One entry per tool family: which commands and output shapes it recognises, which
 * lines carry the signal (`keep`), which are noise (`drop`), which repeat and may be
 * collapsed, and which must survive truncation (`anchor`). `verdicts` replaces the
 * whole output with a one-line summary when a pattern proves the run was clean.
 *
 * Data only - the engine that applies these lives in ./shell. Ordered by descending
 * `priority` at load time, so a specific filter beats the generic fallback.
 */

/** One tool family's rules for stripping its output down to the signal. */
export interface ShellFilter {
    /** Stable id, also the name reported in the compression result. */
    id: string;
    /** Human label for reports and the dashboard. */
    label: string;
    /** Match strength; higher wins when several filters match the same output. */
    priority: number;
    /** Regexes matched against the command line that produced the output. */
    commands?: string[];
    /** Regexes matched against the output itself when no command is known. */
    patterns?: string[];
    /** When any line matches one of these, ONLY matching lines are kept. */
    keep?: string[];
    /** Lines matching these are removed outright. */
    drop?: string[];
    /** Lines matching these are kept once; later identical ones are dropped. */
    collapse?: string[];
    /** Lines matching these survive truncation wherever they sit. */
    anchor?: string[];
    /** Replace the whole output with `message` when `pattern` hits and `unless` does not. */
    verdicts?: Array<{ pattern: string; message: string; unless?: string; }>;
    /** Strip ANSI escape sequences before filtering. */
    stripAnsi?: boolean;
    /** Collapse runs of identical consecutive lines. */
    dedupe?: boolean;
    /** Truncate to this many lines (0/absent = no line cap). */
    maxLines?: number;
    /** Lines kept from the start when truncating. */
    headLines: number;
    /** Lines kept from the end when truncating. */
    tailLines: number;
    /** Stand-in emitted when filtering leaves nothing. */
    onEmpty?: string;
}

export const SHELL_FILTERS: ShellFilter[] = [
    {
        id: "aws",
        label: "AWS CLI",
        priority: 76,
        commands: ["^aws\\b"],
        patterns: [
            "An error occurred \\([A-Za-z0-9]+\\) when calling",
            "^(?:upload|download): ",
        ],
        keep: [
            "^(?:upload|download): ",
            "An error occurred \\(",
        ],
        drop: [
            "^Completed \\d",
            "^\\s*$",
        ],
        anchor: [
            "An error occurred",
            "AccessDenied",
            "Throttling",
            "ValidationError",
            "^(?:upload|download): ",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 40,
    },
    {
        id: "biome",
        label: "Biome",
        priority: 80,
        commands: [
            "^biome\\b",
            "^npx\\s+biome\\b",
        ],
        patterns: [
            "Checked \\d+ files?",
            "biome",
        ],
        keep: [
            "error",
            "warning",
            "✖",
            "Checked",
            "Fixed",
            "^\\s*>",
        ],
        drop: [
            "^\\s*$",
            "^Checked \\d+ files? in",
        ],
        anchor: [
            "error",
            "✖",
            "Checked",
            "Fixed",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 40,
        onEmpty: "biome: ok",
    },
    {
        id: "build-eslint",
        label: "ESLint",
        priority: 88,
        commands: ["^(?:eslint|npm\\s+run\\s+lint)\\b"],
        patterns: [
            "\\s+\\d+:\\d+\\s+(?:error|warning)\\s+",
            "✖\\s+\\d+\\s+problems?",
        ],
        keep: [
            "\\s+\\d+:\\d+\\s+(error|warning)\\s+",
            "✖\\s+\\d+\\s+problems?",
            "^/.*\\.(ts|tsx|js|jsx)$",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "error",
            "warning",
            "problems?",
        ],
        maxLines: 120,
        headLines: 20,
        tailLines: 40,
    },
    {
        id: "build-typescript",
        label: "TypeScript",
        priority: 93,
        commands: ["^(?:tsc|npm\\s+run\\s+typecheck)\\b"],
        patterns: [
            "TS\\d{4}:",
            "error TS\\d{4}",
        ],
        keep: [
            "TS\\d{4}:",
            "error TS\\d{4}",
            "^Found \\d+ errors?",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "TS\\d{4}",
            "Found \\d+",
        ],
        maxLines: 120,
        headLines: 20,
        tailLines: 40,
    },
    {
        id: "build-vite",
        label: "Vite Build",
        priority: 83,
        commands: [
            "^vite\\s+build\\b",
            "^npm\\s+run\\s+build\\b",
            "^pnpm\\s+build\\b",
        ],
        patterns: [
            "vite v[\\d.]+",
            "✓ built in",
        ],
        keep: [
            "error",
            "failed",
            "✓ built in",
            "dist/",
            "rendering chunks",
        ],
        drop: [
            "^transforming ",
            "^✓ \\d+ modules transformed",
            "^\\s*$",
        ],
        collapse: ["^dist/"],
        anchor: [
            "error",
            "failed",
            "✓ built in",
        ],
        verdicts: [
            { pattern: "✓ built in", message: "vite: build ok", unless: "error|failed" },
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 45,
    },
    {
        id: "build-webpack",
        label: "Webpack Build",
        priority: 84,
        commands: [
            "^webpack\\b",
            "^npx\\s+webpack\\b",
        ],
        patterns: [
            "webpack \\d",
            "compiled (?:successfully|with)",
        ],
        keep: [
            "ERROR in",
            "WARNING in",
            "compiled ",
            "asset ",
            "Entrypoint",
        ],
        drop: [
            "^\\s*$",
            "^cacheable modules",
        ],
        collapse: ["^asset "],
        anchor: [
            "ERROR in",
            "compiled ",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 140,
        headLines: 35,
        tailLines: 50,
    },
    {
        id: "bundle-install",
        label: "Bundle Install",
        priority: 70,
        commands: ["^bundle\\s+install\\b"],
        patterns: [
            "Bundle complete",
            "Using ",
        ],
        keep: [
            "Bundle complete",
            "Your bundle is complete",
            "ERROR",
            "Gem::",
        ],
        drop: [
            "^Using ",
            "^Fetching ",
            "^Installing ",
            "^\\s*$",
        ],
        anchor: [
            "ERROR",
            "Gem::",
            "Bundle complete",
            "Your bundle is complete",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 35,
        onEmpty: "bundle: ok",
    },
    {
        id: "composer",
        label: "Composer (PHP)",
        priority: 65,
        commands: [
            "^composer\\s+(?:install|update|require|remove|dump-autoload|outdated)\\b",
            "^php\\s+composer(?:\\.phar)?\\s+(?:install|update|require)\\b",
        ],
        patterns: [
            "Package operations: \\d+ install",
            "Generating (?:optimized )?autoload files",
            "Your requirements could not be resolved",
            "Problem \\d+",
            "vulnerabilities found",
        ],
        keep: [
            "Package operations: \\d+",
            "Generating (?:optimized )?autoload files",
            "Your requirements could not be resolved",
            "Problem \\d+",
            "vulnerabilities found",
            "WARNING",
            "ERROR",
            "Could not (?:find|resolve|delete)",
            "conflicts with",
            "requires .+ but",
            "- (?:Installing|Updating|Removing) \\S+",
            "PHP Fatal error",
            "Class .+ not found",
        ],
        drop: [
            "^\\s*$",
            "^Loading composer repositories",
            "^Updating dependencies",
            "^Writing lock file",
            "^Installing dependencies from lock file",
            "^Downloading \\(\\d+%\\)",
            "^\\s*-\\s+Downloading",
        ],
        collapse: ["^\\s*-\\s+Installing"],
        anchor: [
            "Your requirements could not be resolved",
            "Problem \\d+",
            "ERROR",
            "PHP Fatal error",
            "Class .+ not found",
            "Package operations: \\d+",
            "Generating (?:optimized )?autoload files",
            "vulnerabilities found",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 20,
        tailLines: 50,
    },
    {
        id: "curl",
        label: "curl",
        priority: 70,
        commands: ["^curl\\b"],
        patterns: [
            "curl: \\(\\d+\\)",
            "^HTTP/\\d(?:\\.\\d)? \\d{3}",
        ],
        keep: [
            "^HTTP/\\d(?:\\.\\d)? \\d{3}",
            "^curl: \\(\\d+\\)",
            "^[<{]",
        ],
        drop: [
            "^\\s*% Total\\s+% Received",
            "^\\s*\\d+\\s+\\d+",
            "^\\s*$",
        ],
        anchor: [
            "curl: \\(\\d+\\)",
            "^HTTP/\\d(?:\\.\\d)? [45]\\d\\d",
            "^HTTP/\\d(?:\\.\\d)? \\d{3}",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 30,
        tailLines: 40,
    },
    {
        id: "df",
        label: "df",
        priority: 67,
        commands: ["^df\\b"],
        patterns: ["^Filesystem\\s+.*Use%"],
        keep: [
            "^Filesystem\\s+",
            "^/dev/\\S+\\s+",
        ],
        drop: [
            "^tmpfs\\s",
            "^udev\\s",
            "^\\s*$",
        ],
        anchor: [
            "No such file",
            "Permission denied",
            "Use%",
            "^/dev/",
        ],
        stripAnsi: true,
        maxLines: 80,
        headLines: 25,
        tailLines: 25,
    },
    {
        id: "docker-build",
        label: "Docker Build",
        priority: 82,
        commands: [
            "^docker\\s+(?:build|buildx\\s+build)\\b",
            "^(?:docker\\s+compose|docker-compose)\\s+build\\b",
        ],
        patterns: [
            "Successfully built \\w+",
            "Successfully tagged \\S+",
            "writing image sha256:",
            "ERROR \\[",
            "exit code: \\d+",
        ],
        keep: [
            "ERROR",
            "ERR!",
            "exit code: \\d+",
            "failed to solve",
            "failed to compute cache key",
            "Cannot connect to the Docker daemon",
            "no such file or directory",
            "Successfully built \\w+",
            "Successfully tagged \\S+",
            "writing image sha256:",
            "naming to docker\\.io/\\S+",
            "DONE",
            "^Step \\d+/\\d+ :",
            "Sending build context",
            "WARN\\s*\\[",
        ],
        drop: [
            "^#\\d+\\s+sha256:",
            "^\\s*$",
            "^\\s+\\d+\\.\\d+s$",
            "^\\s*-+>\\s*Running in",
            "^\\s*Removing intermediate container",
            "^\\s*-+>\\s*[a-f0-9]{12}$",
        ],
        collapse: [
            "^#\\d+\\s+CACHED",
            "^\\s*Pulling fs layer",
        ],
        anchor: [
            "ERROR",
            "exit code: \\d+",
            "failed to solve",
            "Cannot connect",
            "Successfully built",
            "Successfully tagged",
            "writing image",
            "DONE",
        ],
        stripAnsi: true,
        maxLines: 100,
        headLines: 15,
        tailLines: 50,
    },
    {
        id: "docker-logs",
        label: "Docker Logs",
        priority: 84,
        commands: ["^docker\\s+(?:compose\\s+)?logs\\b"],
        patterns: [
            "\\b(?:ERROR|WARN|INFO)\\b",
            "^Attaching to ",
        ],
        keep: [
            "ERROR",
            "WARN",
            "Exception",
            "Traceback",
            "failed",
            "listening",
            "started",
        ],
        drop: [
            "^Attaching to ",
            "^\\s*$",
        ],
        collapse: ["INFO"],
        anchor: [
            "ERROR",
            "Exception",
            "failed",
            "started",
            "listening",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 20,
        tailLines: 60,
    },
    {
        id: "docker-ps",
        label: "Docker PS",
        priority: 60,
        commands: ["^docker\\s+ps\\b"],
        patterns: ["^CONTAINER ID\\s+IMAGE\\s+COMMAND"],
        drop: ["^\\s*$"],
        anchor: ["^CONTAINER ID"],
        maxLines: 80,
        headLines: 30,
        tailLines: 20,
    },
    {
        id: "dotnet",
        label: ".NET CLI",
        priority: 78,
        commands: ["^dotnet\\b"],
        patterns: [
            "^Build (?:succeeded|FAILED)\\b",
            "\\b(?:error|warning) CS\\d+\\b",
        ],
        drop: [
            "^Microsoft \\(R\\)",
            "^Copyright \\(C\\) Microsoft",
            "Determining projects to restore",
            "^\\s*Restored ",
            "^\\s*$",
            "^Time Elapsed ",
        ],
        collapse: ["^\\s*Restored "],
        anchor: [
            "Build FAILED",
            "FAILED",
            "\\berror CS\\d+\\b",
            "\\bwarning CS\\d+\\b",
            "Failed!",
            "Build succeeded",
            "Passed!",
            "Total tests:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 40,
        tailLines: 60,
        onEmpty: "dotnet: ok",
    },
    {
        id: "du",
        label: "du",
        priority: 66,
        commands: ["^du\\b"],
        patterns: ["^\\d+(?:\\.\\d+)?[KMGTP]?\\s+\\S+"],
        drop: ["^\\s*$"],
        anchor: [
            "Permission denied",
            "No such file",
            "\\s+\\.$",
            "\\s+total$",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 80,
        headLines: 20,
        tailLines: 30,
    },
    {
        id: "error-stacktrace",
        label: "Error Stacktrace",
        priority: 70,
        patterns: [
            "Traceback \\(most recent call last\\):",
            "^\\s+at\\s+",
            "^panic: ",
        ],
        keep: [
            "Error:",
            "Exception:",
            "Traceback",
            "^\\s+at ",
            "^panic:",
            "^thread ",
            "^Caused by:",
        ],
        drop: ["^\\s*$"],
        collapse: ["^\\s+at "],
        anchor: [
            "Error:",
            "Exception:",
            "^panic:",
            "Traceback",
            "Caused by:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 80,
        headLines: 25,
        tailLines: 30,
    },
    {
        id: "gcloud",
        label: "gcloud",
        priority: 75,
        commands: ["^gcloud\\b"],
        patterns: [
            "^ERROR: \\(gcloud\\.",
            "^Updated property \\[",
        ],
        keep: [
            "^ERROR: \\(gcloud\\.",
            "^Updated property \\[",
            "^Created \\[",
        ],
        drop: [
            "^Waiting for operation",
            "^\\s*$",
        ],
        anchor: [
            "^ERROR: \\(gcloud\\.",
            "PERMISSION_DENIED",
            "NOT_FOUND",
            "^Updated property \\[",
            "^Created \\[",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 40,
    },
    {
        id: "generic-output",
        label: "Generic Output",
        priority: 10,
        patterns: [
            "Error:",
            "Exception:",
            "Traceback \\(most recent call last\\):",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "error",
            "failed",
            "exception",
            "traceback",
        ],
        maxLines: 120,
        headLines: 35,
        tailLines: 45,
    },
    {
        id: "gh",
        label: "GitHub CLI",
        priority: 70,
        commands: ["^gh\\s+(?:pr|issue|repo|run|workflow|release|auth|browse|gist|secret|label|search|status)(?!.*--json)\\b"],
        patterns: [
            "^https?://github\\.com/",
            "Created pull request",
            "Created issue",
            "✓\\s+Logged in",
            "X\\s+\\S+",
            "GraphQL error",
            "HTTP \\d{3}:",
        ],
        keep: [
            "^https?://github\\.com/",
            "Creat(?:ed|ing) pull request",
            "Creat(?:ed|ing) issue",
            "Merged pull request",
            "Closed (?:pull request|issue)",
            "Reopened",
            "✓\\s+",
            "X\\s+\\S+",
            "FAIL",
            "GraphQL error",
            "HTTP \\d{3}:",
            "error:",
            "not found",
            "must be authenticated",
            "rate limit",
            "completed\\s+\\w+",
            "queued\\s+\\w+",
            "in_progress\\s+\\w+",
            "#\\d+\\s+\\S",
        ],
        drop: [
            "^\\s*$",
            "^Showing \\d+ of \\d+",
            "^For more information on output formatting",
        ],
        anchor: [
            "GraphQL error",
            "HTTP \\d{3}:",
            "error:",
            "not found",
            "must be authenticated",
            "rate limit",
            "Creat(?:ed|ing) pull request",
            "Creat(?:ed|ing) issue",
            "Merged pull request",
            "^https?://github\\.com/",
        ],
        stripAnsi: true,
        maxLines: 80,
        headLines: 20,
        tailLines: 40,
    },
    {
        id: "git-branch",
        label: "Git Branch",
        priority: 94,
        commands: ["^git\\s+(?:branch|checkout|switch)\\b"],
        patterns: [
            "^\\*\\s+\\S+",
            "Switched to (?:a new )?branch",
            "Already on",
        ],
        keep: [
            "^\\*\\s+\\S+",
            "^\\s{2}\\S+",
            "Switched to",
            "Already on",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "error",
            "failed",
            "Switched to",
            "Already on",
        ],
        verdicts: [
            { pattern: "Switched to (?:a new )?branch", message: "git: switched branch", unless: "error|failed" },
            { pattern: "Already on", message: "git: already on branch" },
        ],
        stripAnsi: true,
        maxLines: 60,
        headLines: 20,
        tailLines: 20,
    },
    {
        id: "git-diff",
        label: "Git Diff",
        priority: 94,
        commands: ["^git\\s+(?:diff|show)\\b"],
        patterns: [
            "^diff --git ",
            "^@@\\s+-\\d+,\\d+\\s+\\+\\d+,\\d+\\s+@@",
        ],
        drop: [
            "^index [0-9a-f]+\\.\\.[0-9a-f]+.*$",
            "^--- a/",
            "^\\+\\+\\+ b/",
        ],
        collapse: ["^\\s*$"],
        anchor: [
            "^diff --git ",
            "^@@ ",
            "^[+-](?![+-]{2})",
        ],
        dedupe: true,
        maxLines: 180,
        headLines: 40,
        tailLines: 50,
    },
    {
        id: "git-log",
        label: "Git Log",
        priority: 70,
        commands: ["^git\\s+log\\b"],
        patterns: [
            "^commit [0-9a-f]{7,40}",
            "^Author: ",
        ],
        keep: [
            "^commit [0-9a-f]{7,40}",
            "^\\s{4}\\S",
        ],
        drop: [
            "^Author: ",
            "^Date: ",
            "^\\s*$",
        ],
        anchor: ["^commit "],
        maxLines: 120,
        headLines: 40,
        tailLines: 20,
    },
    {
        id: "git-status",
        label: "Git Status",
        priority: 95,
        commands: ["^git\\s+status\\b"],
        patterns: [
            "^On branch ",
            "^Changes (?:not staged|to be committed)",
            "^Untracked files:",
        ],
        keep: [
            "^On branch ",
            "^Your branch ",
            "^Changes ",
            "^Untracked files:",
            "^\\s*(modified|new file|deleted|renamed|both modified):",
            "^\\s*[MADRCU?!]{1,2}\\s+",
        ],
        drop: [
            "^\\s*$",
            "^\\s*\\(use .*\\)$",
        ],
        anchor: [
            "^Changes ",
            "^Untracked files:",
        ],
        maxLines: 80,
        headLines: 12,
        tailLines: 20,
    },
    {
        id: "golangci-lint",
        label: "golangci-lint",
        priority: 82,
        commands: ["^golangci-lint\\b"],
        patterns: [
            "issues:",
            "level=error",
            ":\\d+:\\d+:",
        ],
        keep: [
            ":\\d+:\\d+:",
            "level=error",
            "issues:",
            "Error:",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "level=error",
            "Error:",
            "issues:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 140,
        headLines: 35,
        tailLines: 50,
    },
    {
        id: "gradle",
        label: "Gradle",
        priority: 78,
        commands: ["^(?:gradle|gradlew|\\./gradlew)\\b"],
        patterns: [
            "^> Task :",
            "^BUILD (?:SUCCESSFUL|FAILED)\\b",
        ],
        drop: [
            "^Welcome to Gradle",
            "^Starting a Gradle Daemon",
            "^> Task :\\S+ (?:UP-TO-DATE|SKIPPED|NO-SOURCE|FROM-CACHE)$",
            "^Download https?://",
            "^\\s*$",
        ],
        collapse: ["^> Task :\\S+$"],
        anchor: [
            "BUILD FAILED",
            "FAILED",
            "What went wrong",
            "Caused by:",
            "error:",
            "> Task :\\S+ FAILED",
            "BUILD SUCCESSFUL",
            "actionable task",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 40,
        tailLines: 60,
        onEmpty: "gradle: ok",
    },
    {
        id: "json-output",
        label: "JSON Output",
        priority: 70,
        commands: ["^(?:jq\\b|cat\\s+.*\\.json\\b)"],
        patterns: ["^\\s*[\\[{][\\s\\S]*[\\]}]\\s*$"],
        keep: [
            "\"status\"\\s*:",
            "\"error\"\\s*:",
            "\"errors\"\\s*:",
            "\"code\"\\s*:",
            "\"message\"\\s*:",
            "[{}\\[\\],]",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "\"error\"",
            "\"errors\"",
            "\"message\"",
        ],
        maxLines: 120,
        headLines: 20,
        tailLines: 30,
    },
    {
        id: "kubectl",
        label: "kubectl",
        priority: 78,
        commands: ["^kubectl\\s+(?:get|describe|apply|delete|rollout|events?)(?!.*(?:-o|--output)(?:\\s+|=)(?:json|yaml|go-template|jsonpath|template|name))\\b"],
        patterns: [
            "NAME\\s+READY\\s+STATUS",
            "NAME\\s+TYPE\\s+CLUSTER-IP",
            "CrashLoopBackOff",
            "ImagePullBackOff",
            "ErrImagePull",
            "FailedScheduling",
            "OOMKilled",
            "Error from server",
        ],
        keep: [
            "Error from server",
            "CrashLoopBackOff",
            "ImagePullBackOff",
            "ErrImagePull",
            "FailedScheduling",
            "OOMKilled",
            "Evicted",
            "ContainerCannotRun",
            "BackOff",
            "Unhealthy",
            "Killing",
            "Restarting",
            "NAME\\s+READY\\s+STATUS",
            "NAME\\s+TYPE\\s+CLUSTER-IP",
            "Warning\\s+",
            "deployment\\.apps/\\S+\\s+(?:created|configured|unchanged)",
            "service/\\S+\\s+(?:created|configured)",
            "pod/\\S+\\s+(?:created|deleted)",
            "rollout (?:status|history)",
            "successfully rolled out",
        ],
        drop: [
            "^\\s*$",
            "^\\s*creationTimestamp:",
            "^\\s*resourceVersion:",
            "^\\s*uid:",
            "^\\s*managedFields:",
            "^\\s*selfLink:",
            "^\\s*generation:",
        ],
        collapse: [
            "Normal\\s+",
            "^\\s*-\\s+lastTransitionTime:",
        ],
        anchor: [
            "Error from server",
            "CrashLoopBackOff",
            "ImagePullBackOff",
            "OOMKilled",
            "FailedScheduling",
            "Evicted",
            "successfully rolled out",
            "deployment\\.apps/\\S+\\s+\\w+",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 20,
        tailLines: 60,
    },
    {
        id: "make",
        label: "Make",
        priority: 78,
        commands: ["^make\\b"],
        patterns: ["make\\[\\d+\\]: (?:Entering|Leaving) directory"],
        drop: [
            "^make\\[\\d+\\]: (?:Entering|Leaving) directory",
            "^\\s*$",
            "Nothing to be done for",
        ],
        collapse: ["^(?:cc|gcc|clang|g\\+\\+)\\b"],
        anchor: [
            "error:",
            "failed",
            "\\*\\*\\*",
            "built",
            "linking",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 40,
        onEmpty: "make: ok",
    },
    {
        id: "mypy",
        label: "mypy",
        priority: 82,
        commands: [
            "^mypy\\b",
            "^python\\s+-m\\s+mypy\\b",
        ],
        patterns: [
            ": error:",
            "Found \\d+ errors? in",
        ],
        keep: [
            ": error:",
            ": note:",
            "Found \\d+ errors?",
            "Success: no issues found",
        ],
        drop: ["^\\s*$"],
        anchor: [
            ": error:",
            "Found \\d+ errors?",
            "Success:",
            "Found \\d+",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 40,
        tailLines: 60,
    },
    {
        id: "npm-audit",
        label: "npm audit",
        priority: 84,
        commands: ["^(?:npm|pnpm|yarn)\\s+audit\\b"],
        patterns: [
            "found \\d+ vulnerabilities",
            "\\bcritical\\b",
        ],
        keep: [
            "vulnerabilities",
            "critical",
            "high",
            "moderate",
            "low",
            "fix available",
            "npm audit fix",
            "No vulnerabilities",
        ],
        drop: [
            "^\\s*$",
            "^# npm audit report",
        ],
        anchor: [
            "critical",
            "high",
            "vulnerabilities",
            "No vulnerabilities",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 45,
    },
    {
        id: "npm-install",
        label: "Package Install",
        priority: 65,
        commands: ["^(?:npm|pnpm|yarn)\\s+(?:install|add|update)\\b"],
        patterns: [
            "added \\d+ packages",
            "packages are looking for funding",
            "audited \\d+ packages",
        ],
        keep: [
            "added \\d+ packages",
            "removed \\d+ packages",
            "changed \\d+ packages",
            "audited \\d+ packages",
            "vulnerabilities",
            "WARN",
            "ERR!",
        ],
        drop: [
            "^\\s*$",
            "^\\s*\\|",
            "^Progress:",
        ],
        anchor: [
            "WARN",
            "ERR",
            "vulnerabilities",
        ],
        maxLines: 80,
        headLines: 20,
        tailLines: 30,
    },
    {
        id: "nx",
        label: "Nx",
        priority: 76,
        commands: [
            "^nx\\b",
            "^npx\\s+nx\\b",
        ],
        patterns: [
            "NX   ",
            "Successfully ran target",
        ],
        keep: [
            "NX   ",
            "ERROR",
            "Failed",
            "Successfully ran",
            "Running target",
        ],
        drop: [
            "^\\s*$",
            "^> nx run",
        ],
        anchor: [
            "ERROR",
            "Failed",
            "Successfully ran",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 25,
        tailLines: 50,
    },
    {
        id: "pip",
        label: "pip",
        priority: 72,
        commands: [
            "^pip\\s+(?:install|sync|download)\\b",
            "^python\\s+-m\\s+pip\\s+install\\b",
        ],
        patterns: [
            "Successfully installed",
            "Requirement already satisfied",
        ],
        keep: [
            "Successfully installed",
            "ERROR:",
            "WARNING:",
            "failed",
            "Could not find",
        ],
        drop: [
            "^Collecting ",
            "^Downloading ",
            "^Installing collected packages:",
            "^Requirement already satisfied",
            "^\\s*$",
        ],
        anchor: [
            "ERROR:",
            "failed",
            "Could not find",
            "Successfully installed",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 35,
        onEmpty: "pip: ok",
    },
    {
        id: "playwright",
        label: "Playwright",
        priority: 86,
        commands: [
            "^playwright\\s+test\\b",
            "^npx\\s+playwright\\s+test\\b",
        ],
        patterns: [
            "Running \\d+ tests?",
            "Error Context:",
            "failed",
        ],
        keep: [
            "✘",
            "Error:",
            "Error Context:",
            "failed",
            "passed",
            "Slow test file",
            "^\\s*\\d+\\)",
        ],
        drop: [
            "^\\s*$",
            "^Running \\d+ tests? using",
        ],
        collapse: ["^\\s+at "],
        anchor: [
            "Error:",
            "✘",
            "failed",
            "passed",
            "failed",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 35,
        tailLines: 60,
    },
    {
        id: "poetry-install",
        label: "Poetry Install",
        priority: 72,
        commands: ["^poetry\\s+(?:install|update)\\b"],
        patterns: [
            "Package operations:",
            "Installing dependencies",
        ],
        keep: [
            "Package operations:",
            "Writing lock file",
            "Error",
            "failed",
        ],
        drop: [
            "^  - Installing ",
            "^  - Updating ",
            "^Installing dependencies",
            "^\\s*$",
        ],
        anchor: [
            "Error",
            "failed",
            "Package operations:",
            "Writing lock file",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 35,
        onEmpty: "poetry: ok",
    },
    {
        id: "prettier",
        label: "Prettier",
        priority: 79,
        commands: [
            "^prettier\\b",
            "^npx\\s+prettier\\b",
        ],
        patterns: [
            "\\[warn\\]",
            "All matched files use Prettier",
        ],
        keep: [
            "\\[warn\\]",
            "Code style issues",
            "All matched files",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "\\[error\\]",
            "Code style issues",
            "All matched files",
        ],
        verdicts: [
            { pattern: "All matched files use Prettier", message: "prettier: ok" },
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 80,
        headLines: 20,
        tailLines: 30,
    },
    {
        id: "ps",
        label: "ps",
        priority: 68,
        commands: ["^ps\\b"],
        patterns: ["^(?:USER\\s+PID|\\s*PID\\s+)"],
        keep: [
            "^(?:USER\\s+PID|\\s*PID\\s+)",
            "^\\S+\\s+\\d+\\s+",
            "^\\s*\\d+\\s+",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "defunct",
            "Permission denied",
            "^(?:USER\\s+PID|\\s*PID\\s+)",
        ],
        stripAnsi: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 50,
    },
    {
        id: "rsync",
        label: "rsync",
        priority: 73,
        commands: ["^rsync\\b"],
        patterns: [
            "^sending incremental file list",
            "^rsync error:",
        ],
        drop: [
            "^sending incremental file list",
            "^sent \\d",
            "^total size is",
            "^\\s*$",
        ],
        anchor: [
            "^rsync error:",
            "Permission denied",
            "No such file",
            "^sent \\d",
            "^total size is",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 140,
        headLines: 35,
        tailLines: 50,
    },
    {
        id: "rubocop",
        label: "RuboCop",
        priority: 74,
        commands: [
            "^rubocop\\b",
            "^bundle\\s+exec\\s+rubocop\\b",
        ],
        patterns: [
            "^Inspecting \\d+ files",
            "^\\S+\\.rb:\\d+:\\d+: [A-Z]:",
        ],
        keep: [
            "^\\S+\\.rb:\\d+:\\d+: [A-Z]:",
            "^\\d+ files inspected",
        ],
        drop: [
            "^Inspecting \\d+ files",
            "^\\.+$",
            "^\\s*$",
        ],
        anchor: [
            " [EF]: ",
            "Offenses:",
            "^\\d+ files inspected",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 45,
    },
    {
        id: "ruff",
        label: "Ruff",
        priority: 82,
        commands: [
            "^ruff\\b",
            "^uv\\s+run\\s+ruff\\b",
        ],
        patterns: [
            "Found \\d+ errors?",
            "All checks passed",
        ],
        keep: [
            "^[A-Z]\\d{3}",
            "Found \\d+",
            "error:",
            "warning:",
            "-->",
        ],
        drop: ["^\\s*$"],
        anchor: [
            "^[A-Z]\\d{3}",
            "error:",
            "Found \\d+",
            "All checks passed",
        ],
        verdicts: [
            { pattern: "All checks passed", message: "ruff: ok" },
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 30,
        tailLines: 40,
    },
    {
        id: "shell-find",
        label: "find",
        priority: 80,
        commands: ["^find\\b"],
        patterns: ["^(?:\\./|/|[A-Za-z0-9_.-]+/)"],
        drop: ["^\\s*$"],
        anchor: [
            "Permission denied",
            "No such file",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 40,
        tailLines: 40,
    },
    {
        id: "shell-grep",
        label: "grep/rg",
        priority: 82,
        commands: ["^(?:grep|rg|ag)\\b"],
        patterns: [
            "^[\\w./-]+\\.(?:ts|tsx|js|jsx|py|go|rs|java|rb|md|json|ya?ml|txt):\\d*:",
            "^[\\w./-]+/[\\w./-]+:\\d*:",
        ],
        keep: ["^[\\w./-]+(?::\\d+)?:"],
        drop: ["^\\s*$"],
        anchor: [
            "No such file",
            "Permission denied",
            "^[^:\\n]+(?::\\d+)?:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 40,
        tailLines: 60,
    },
    {
        id: "shell-ls",
        label: "Shell Listing",
        priority: 50,
        commands: ["^(?:ls(?:\\s+-[A-Za-z]+)?|find)\\b"],
        patterns: [
            "^total \\d+",
            "^\\S+\\s+\\S+\\s+\\d+\\s+\\w+\\s+\\d{1,2}\\s+",
        ],
        drop: ["^\\s*$"],
        anchor: ["^total \\d+"],
        maxLines: 100,
        headLines: 40,
        tailLines: 30,
    },
    {
        id: "ssh",
        label: "ssh",
        priority: 72,
        commands: ["^ssh\\b"],
        patterns: [
            "Permission denied \\(",
            "Host key verification failed",
            "Connection (?:closed|timed out)",
        ],
        keep: [
            "Permission denied",
            "Host key verification failed",
            "Connection (?:closed|timed out)",
            "^Welcome ",
        ],
        drop: [
            "^debug\\d:",
            "^\\s*$",
        ],
        anchor: [
            "Permission denied",
            "Host key verification failed",
            "Connection timed out",
            "^Welcome ",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 40,
    },
    {
        id: "systemctl-status",
        label: "systemctl status",
        priority: 77,
        commands: ["^systemctl\\s+status\\b"],
        patterns: [
            "Loaded:",
            "Active:",
            "Main PID:",
        ],
        keep: [
            "Loaded:",
            "Active:",
            "Main PID:",
            "CGroup:",
            "error",
            "failed",
            "Started",
            "Stopped",
        ],
        drop: ["^\\s*$"],
        collapse: ["^\\s+Docs:"],
        anchor: [
            "failed",
            "error",
            "Active:",
            "Loaded:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 30,
        tailLines: 40,
    },
    {
        id: "terraform-plan",
        label: "Terraform Plan",
        priority: 88,
        commands: ["^terraform\\s+plan\\b"],
        patterns: [
            "Terraform will perform the following actions",
            "Plan: \\d+ to add",
        ],
        keep: [
            "Terraform will perform",
            "^[ ]*[#~+\\-/]",
            "Plan: \\d+",
            "Error:",
        ],
        drop: [
            "Refreshing state",
            "Acquiring state lock",
            "Releasing state lock",
            "^\\s*$",
        ],
        anchor: [
            "Error:",
            "failed",
            "Plan: \\d+",
        ],
        stripAnsi: true,
        maxLines: 160,
        headLines: 35,
        tailLines: 50,
    },
    {
        id: "test-cargo",
        label: "Cargo Test",
        priority: 90,
        commands: ["^cargo\\s+(?:test|nextest)\\b"],
        patterns: [
            "^running \\d+ tests?",
            "test result:",
        ],
        keep: [
            "^running \\d+ tests?",
            "^test .* \\.\\.\\. FAILED",
            "^failures:",
            "^---- ",
            "^thread ",
            "^test result:",
            "^error:",
        ],
        drop: [
            "^test .* \\.\\.\\. ok$",
            "^\\s*$",
        ],
        collapse: ["^\\s+at "],
        anchor: [
            "FAILED",
            "^error:",
            "^thread ",
            "test result:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 180,
        headLines: 40,
        tailLines: 70,
    },
    {
        id: "test-go",
        label: "Go Test",
        priority: 90,
        commands: ["^go\\s+test\\b"],
        patterns: [
            "^--- FAIL:",
            "^(?:ok|FAIL)\\s+",
        ],
        keep: [
            "^--- FAIL:",
            "^FAIL",
            "^ok\\s+",
            "^panic:",
            "^\\s+.*_test\\.go:\\d+",
            "^\\s*Error",
        ],
        drop: ["^\\s*$"],
        collapse: ["^=== RUN"],
        anchor: [
            "^--- FAIL:",
            "^panic:",
            "^FAIL",
            "^ok\\s+",
            "^FAIL\\s+",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 160,
        headLines: 35,
        tailLines: 60,
    },
    {
        id: "test-jest",
        label: "Jest",
        priority: 90,
        commands: ["^(?:jest|npm\\s+(?:run\\s+)?test)\\b"],
        patterns: [
            "Test Suites:\\s+\\d+",
            "Tests:\\s+\\d+",
            "^PASS\\s+",
            "^FAIL\\s+",
        ],
        keep: [
            "^FAIL\\s+",
            "^\\s*●\\s+",
            "Expected:",
            "Received:",
            "Test Suites:",
            "Tests:",
            "Snapshots:",
            "Time:",
            "\\s+at\\s+",
        ],
        drop: [
            "^PASS\\s+",
            "^\\s*✓\\s+",
        ],
        collapse: ["^\\s*at "],
        anchor: [
            "FAIL",
            "Expected:",
            "Received:",
            "Test Suites:",
        ],
        dedupe: true,
        maxLines: 140,
        headLines: 24,
        tailLines: 50,
    },
    {
        id: "test-pytest",
        label: "Pytest",
        priority: 90,
        commands: ["^(?:pytest|python\\s+-m\\s+pytest)\\b"],
        patterns: [
            "=+\\s+(?:\\d+\\s+)?(?:passed|failed|errors?)",
            "^E\\s+",
            "^FAILED ",
        ],
        keep: [
            "^FAILED ",
            "^ERROR ",
            "^E\\s+",
            "Traceback \\(most recent call last\\):",
            "=+ short test summary info =+",
            "=+ .*failed",
            "AssertionError",
        ],
        drop: [
            "^\\.",
            "^\\s*$",
        ],
        collapse: ["^E\\s+"],
        anchor: [
            "FAILED",
            "ERROR",
            "Traceback",
            "AssertionError",
        ],
        dedupe: true,
        maxLines: 160,
        headLines: 28,
        tailLines: 60,
    },
    {
        id: "test-vitest",
        label: "Vitest",
        priority: 92,
        commands: ["^(?:vitest|npm\\s+(?:run\\s+)?test:vitest)\\b"],
        patterns: [
            "\\bvitest\\b",
            "^ ✓ ",
            "^ ❯ ",
            "Test Files\\s+\\d+\\s+(?:passed|failed)",
        ],
        keep: [
            "^\\s*FAIL\\s+",
            "^\\s*❯\\s+",
            "^\\s*×\\s+",
            "Test Files\\s+",
            "Tests\\s+",
            "Duration\\s+",
            "Error:",
            "AssertionError",
            "\\s+at\\s+",
        ],
        drop: [
            "^\\s*✓\\s+",
            "^\\s*stdout \\|",
            "^\\s*stderr \\|",
        ],
        collapse: ["^\\s*at "],
        anchor: [
            "FAIL",
            "Error:",
            "AssertionError",
            "Test Files",
        ],
        dedupe: true,
        maxLines: 140,
        headLines: 24,
        tailLines: 50,
    },
    {
        id: "tofu-plan",
        label: "OpenTofu Plan",
        priority: 87,
        commands: ["^tofu\\s+plan\\b"],
        patterns: [
            "OpenTofu will perform the following actions",
            "Plan: \\d+ to add",
        ],
        keep: [
            "OpenTofu will perform",
            "^[ ]*[#~+\\-/]",
            "Plan: \\d+",
            "Error:",
        ],
        drop: [
            "Refreshing state",
            "Acquiring state lock",
            "Releasing state lock",
            "^\\s*$",
        ],
        anchor: [
            "Error:",
            "failed",
            "Plan: \\d+",
        ],
        stripAnsi: true,
        maxLines: 160,
        headLines: 35,
        tailLines: 50,
    },
    {
        id: "turbo",
        label: "Turborepo",
        priority: 76,
        commands: [
            "^turbo\\b",
            "^npx\\s+turbo\\b",
        ],
        patterns: [
            "Tasks:",
            "Remote caching",
        ],
        keep: [
            "failed",
            "error",
            "Tasks:",
            "Cached:",
            "Time:",
            "successful",
        ],
        drop: [
            "cache hit",
            "cache miss",
            "^\\s*$",
        ],
        collapse: ["^• Packages in scope"],
        anchor: [
            "failed",
            "error",
            "Tasks:",
            "Cached:",
            "Time:",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 120,
        headLines: 25,
        tailLines: 50,
    },
    {
        id: "uv-sync",
        label: "uv sync",
        priority: 72,
        commands: [
            "^uv\\s+sync\\b",
            "^uv\\s+pip\\s+install\\b",
        ],
        patterns: [
            "Resolved \\d+ packages?",
            "Prepared \\d+ packages?",
        ],
        keep: [
            "error",
            "failed",
            "Installed",
            "Uninstalled",
            "Resolved",
        ],
        drop: [
            "^Resolved ",
            "^Prepared ",
            "^Installed ",
            "^ \\+",
            "^\\s*$",
        ],
        anchor: [
            "error",
            "failed",
            "Installed",
            "Resolved",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 35,
        onEmpty: "uv: ok",
    },
    {
        id: "wget",
        label: "wget",
        priority: 70,
        commands: ["^wget\\b"],
        patterns: [
            "^--\\d{4}-\\d{2}-\\d{2}",
            "^ERROR \\d{3}:",
        ],
        keep: [
            "^ERROR \\d{3}:",
            "saved \\[\\d",
            "^HTTP request sent",
        ],
        drop: [
            "^\\s*\\d+K",
            "^Saving to:",
            "^\\s*$",
        ],
        anchor: [
            "^ERROR \\d{3}:",
            "failed",
            "unable to resolve",
            "saved \\[\\d",
            "^HTTP request sent",
        ],
        stripAnsi: true,
        dedupe: true,
        maxLines: 100,
        headLines: 25,
        tailLines: 40,
    },
];
